### ISSUE TITLE
support build this repository into debian package

### ISSUE THREAD

**Issue by changchengx** [libbpf/libbpf#120]
What's about adding build rule and script to build out debian package?

**Comment by anakryiko** [comment]
So far packagers of respective Linux distributions have maintained their own build scripts. E.g., there was a PR to get Fedora packaging story discussed, but it was never merged, because packager preferred to keep that on their side. Do you have any specific build rules/scripts in mind you think need to be part of libbpf repo itself?

**Comment by changchengx** [comment]
I understand the packager's concern. However, the distributed packages are not always the newer version which has fixed some bugs or upgraded to match with the new kernel version installed in client's machine.
If the source code includes the package rule, such as debian package rule, developers could generate the package by themselves. This is especially useful when installing package on lots of machines and make it under packager manager software's control.
Even, the package's rule has been added into repository. The linux distributions packager could also generate the package to be relased in various distributions.

**Comment by wat-ze-hex** [comment]
@changchengx 
jfyi, there is a [bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=950760) opened in to switch libbpf from kernel sources to the mirror. v0.0.6 should happen soon. I'll ask its author to subscribe to libbpf tag update notifications so he can bump the version soon enough.
IMO a single source of truth is better, that's why I closed https://github.com/libbpf/libbpf/pull/64 after RPM was published.

**Comment by changchengx** [comment]
I totally agree with you that "IMO a single source of truth is better".
It's also true that package rule maybe not needed in libbpf or some other projects.
Software users could wait for the linux distribution vendor to upgrade the package.
However, I've met with some cases on distributed deployed system i.e. Developer want to upgrade kernel/library/development tools and so on. But the bad news is that not every developer knows how to package the built software into proper format e.g. debian or rpm. It also spent their lots of time on learning how to the package the software.
I suppose that the package rule could be also integrated into source code. The package rule may be not strictly aligned with OS distribution's package rule, but it should work at least.5

**Comment by bluca** [comment]
My 2c: I'd recommend to avoid this. The /usr/local hierarchy has always existed for local builds. In my experience upstream packaging scripts tend to bitrot very quickly, and to diverge from the actual distributions in ways that often lead to severe incompatibilities that break cross-grades.

**Comment by anakryiko** [comment]
right, let's leave packaging to the experts in respective distributions, then.
