### ISSUE TITLE
0.0.9: missing declaratios in header files

### ISSUE THREAD

**Issue by kloczek** [libbpf/libbpf#162]
Installed in $(ncludedir)/bpf header files do not provide all necessary declarations.
For example in bpf.h is:
```
[tkloczko@barrel bpf]$ grep bpf_stats_type *
bpf.h:LIBBPF_API int bpf_enable_stats(enum bpf_stats_type type);
```
That `bpf_stats_type ` is source tree:
```
[tkloczko@barrel libbpf-0.0.9]$ grep bpf_stats_type -r
include/uapi/linux/bpf.h:enum bpf_stats_type {
src/bpf.c:int bpf_enable_stats(enum bpf_stats_type type)
src/bpf.h:LIBBPF_API int bpf_enable_stats(enum bpf_stats_type type);
```
however `include/uapi/linux/bpf.h` is not installed.

**Comment by anakryiko** [comment]
`include/uapi/linux/bpf.h` is not supposed to be installed on target system, it's used to build libbpf itself. But because libbpf's bpf.h header is referencing enum bpf_stats_type, on systems that don't have latest system-wide bpf.h header this will cause compilation error.

We can work around that with enum forward-declaration. I'll send a patch in a second and will sync it here immediately when it is accepted in kernel repo. Thanks for reporting!

**Comment by anakryiko** [comment]
I've updated v0.0.9 to include the fix with forward declared enum bpf_stats_type. Please re-pull.
