### ISSUE TITLE
libbpf 1.0: refactor btf_dump__new API and btf_dump_opts

### ISSUE THREAD

**Issue by anakryiko** [libbpf/libbpf#283]
Details: https://github.com/libbpf/libbpf/wiki/Libbpf:-the-road-to-v1.0#btfh-apis

**Comment by martinetd** [comment]
Hello (not sure if this is the right place to discuss, happy to send a mail to bpf@vger or otherwise, but since this issue preexisted I'm going to assume you use these)

this seems to break build with bpftrace, see https://github.com/iovisor/bpftrace/issues/2068 (build error in the first message)

It looks like the C++ compiler doesn't like the `typeof` macro - this one can be replaced by `__typeof__` which is compatible with both C and C++ compilers . . . but then it also complains `__builtin_types_compatible_p` is was not declared either, and I don't see any c++-compiler-compatible alternative for this one.

The "normal" C++ way would be to just alias all functions to the same name and let the compiler deal with it with its type-annotated symbol names, but we can't use it in extern C, so the best I could come up with was something ugly like this (and quite frankly I'm not suggesting to do this, this would look horrible in backtraces/gdb...):

```diff
diff --git a/src/btf.h b/src/btf.h
index 742a2bf71c5e..5847f070d780 100644
--- a/src/btf.h
+++ b/src/btf.h
@@ -276,6 +276,20 @@ struct btf_dump_opts {
 
 typedef void (*btf_dump_printf_fn_t)(void *ctx, const char *fmt, va_list args);
 
+
+#ifdef __cplusplus
+/* C++ cannot use the same detection mechanism with __builtin_types_compatible_p
+ * as C here, instead just alias all functions to the same name and let the compiler
+ * sort which one to use
+ */
+extern "C++" {
+#define btf_dump__new_v0_6_0 btf_dump__new
+#define btf_dump__new_deprecated btf_dump__new
+#else
+// #define btf_dump__new_v0_6_0 xxx find c++ symbol name
+#define btf_dump__new_deprecated _Z13btf_dump__newPK3btfPK7btf_extPK13btf_dump_optsPFvPvPKcP13__va_list_tagE
+#endif
+
 LIBBPF_API struct btf_dump *btf_dump__new(const struct btf *btf,
 					  btf_dump_printf_fn_t printf_fn,
 					  void *ctx,
@@ -291,6 +305,9 @@ LIBBPF_API struct btf_dump *btf_dump__new_deprecated(const struct btf *btf,
 						     const struct btf_dump_opts *opts,
 						     btf_dump_printf_fn_t printf_fn);
 
+#ifdef __cplusplus
+} // extern C++
+#else
 /* Choose either btf_dump__new() or btf_dump__new_deprecated() based on the
  * type of 4th argument. If it's btf_dump's print callback, use deprecated
  * API; otherwise, choose the new btf_dump__new(). ___libbpf_override()
@@ -319,6 +336,7 @@ LIBBPF_API struct btf_dump *btf_dump__new_deprecated(const struct btf *btf,
 	__builtin_types_compatible_p(typeof(a4), void(void *, const char *, va_list)),	\
 	btf_dump__new_deprecated((void *)a1, (void *)a2, (void *)a3, (void *)a4),	\
 	btf_dump__new((void *)a1, (void *)a2, (void *)a3, (void *)a4))
+#endif
 
 LIBBPF_API void btf_dump__free(struct btf_dump *d);
 
```

A better alternative to me would be to just drop the type autodetection, while it looks nice on paper I've never seen any library implement such an API and it's quite confusing to me (it seems mostly used for dealing with different kind of floats in C)
Versioned symbols so libbpf.so stays binary compatible is good, just make the user explicitly pick which they want at compile time.

Of course bpftrace (and any other c++ user) could just avoid these aliases and do just that, calling `btf_dump__new_deprecated` directly builds just fine as long as the `btf_dump__new` macro is not used, but I'd rather hear your opinion on this first.

Thanks!

**Comment by chenhengqi** [comment]
`__builtin_types_compatible_p` is a GCC builtin, but clang also support it.

https://clang.llvm.org/docs/LanguageExtensions.html#builtin-functions

The problem is that `__builtin_types_compatible_p` is specific to C.

https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html

> Note: This construct is only available for C.

**Comment by martinetd** [comment]
Yes, exactly. src/btf.h has an `extern "C" {` block wrapper for C++ but that is not enough to bring these builtins back unfortunately, so either we can find a portable way to go about it or I'm not quite sure what could be done.

**Comment by anakryiko** [comment]
@martinetd I wish you guys reported it 19 days ago when you first spotted it...

Please also don't use btf_dump__new_v0_6_0 directly, it should be either btf_dump__new (which aliases to btf_dump__new_v0_6_0) or btf_dump__new_deprecated.

Keep in mind, btw, that btf_dump__new_deprecated() will go away in libbpf 1.0, so please ahead on what you are going to do about that, because you chose to not use statically linked vendored libbpf.

As for __typeof__ vs typeof, we can fix that. For __builtin_types_compatible_p no idea for now, worst case I can just detect cplusplus and just not perform this redirection based on types. This redirection is temporary until we release 1.0 and can drop deprecated btf_dump__new_deprecated. But for now we need it to keep compiling existing applications that used old-style btf_dump__new.

**Comment by anakryiko** [comment]
@martinetd can you try if this works, that's the simplest way to do this. You'll have to pick explicitly deprecated vs non-deprecated variant, of course.

```
$ git diff btf.h
diff --git a/tools/lib/bpf/btf.h b/tools/lib/bpf/btf.h
index 742a2bf71c5e..4dbdb4168f66 100644
--- a/tools/lib/bpf/btf.h
+++ b/tools/lib/bpf/btf.h
@@ -314,11 +314,17 @@ LIBBPF_API struct btf_dump *btf_dump__new_deprecated(const struct btf *btf,
  * The rest works just like in case of ___libbpf_override() usage with symbol
  * versioning.
  */
+/* C++ compilers don't support __builtin_types_compatible_p(), so at least
+ * don't screw up compilation for them and let C++ users pick btf_dump__new vs
+ * btf_dump__new_deprecated explicitly.
+ */
+#ifndef __cplusplus
 #define btf_dump__new(a1, a2, a3, a4) __builtin_choose_expr(                           \
        __builtin_types_compatible_p(typeof(a4), btf_dump_printf_fn_t) ||               \
        __builtin_types_compatible_p(typeof(a4), void(void *, const char *, va_list)),  \
        btf_dump__new_deprecated((void *)a1, (void *)a2, (void *)a3, (void *)a4),       \
        btf_dump__new((void *)a1, (void *)a2, (void *)a3, (void *)a4))
+#endif

 LIBBPF_API void btf_dump__free(struct btf_dump *d);
```

**Comment by martinetd** [comment]
First, thanks for the quick reply. (I also wish it'd been reported earlier :-D but let's do with what we have!)

> Keep in mind, btw, that btf_dump__new_deprecated() will go away in libbpf 1.0, so please ahead on what you are going to do about that, because you chose to not use statically linked vendored libbpf.

If it's just a temporary state which will go away then I think we can just stay like this and work around it in bpftrace

> ```
> +/* C++ compilers don't support __builtin_types_compatible_p(), so at least
> + * don't screw up compilation for them and let C++ users pick btf_dump__new vs
> + * btf_dump__new_deprecated explicitly.
> + */
> +#ifndef __cplusplus
>  #define btf_dump__new(a1, a2, a3, a4) __builtin_choose_expr(                           \
>        __builtin_types_compatible_p(typeof(a4), btf_dump_printf_fn_t) ||               \
>        __builtin_types_compatible_p(typeof(a4), void(void *, const char *, va_list)),  \
>        btf_dump__new_deprecated((void *)a1, (void *)a2, (void *)a3, (void *)a4),       \
>        btf_dump__new((void *)a1, (void *)a2, (void *)a3, (void *)a4))
> +#endif
> ```

That's pretty much my current workaround that I used for [nixos](https://github.com/NixOS/nixpkgs/pull/148535/commits/fa857bb4357937a20675ae1ef49cf37e54e2f20c) when I stumbled upon this yesterday - since it's in a macro as long as it's not used then there's no problem in using bpf/btf.h - we don't even need to hide the define (although it'd probably make the error easier to understand if we do)

As it's temporary bpftrace can just detect if btf_dump__new_deprecated exists or base itself on libbpf version and use the right function; it's a bit of a hassle but it's temporary hassle so it sounds acceptable to me, and the same logic can be used to switch to the new API when we're ready for it.
@fbs what do you think?

**Comment by anakryiko** [comment]
Ok, I think bpftrace is one of the few applications that use btf_dump__xxx() APIs, so I think the impact should be minimal, if you can work around on your side. Thanks!
