### ISSUE TITLE
libbpf 1.0: decide the fate of libbpf feature probing and other convenience helpers

### ISSUE THREAD

**Issue by anakryiko** [libbpf/libbpf#312]
Details: https://github.com/libbpf/libbpf/wiki/Libbpf:-the-road-to-v1.0#libbpfh-high-level-apis

**Comment by wat-ze-hex** [comment]
Probe helpers are used in systemd: 
* `bpf_probe_prog_type()` identifies whether the kernel supports socket bind hooks: 
https://github.com/systemd/systemd/blob/main/src/core/bpf-socket-bind.c#L132-L134

* In pre-libbpf code, a [trivial](https://github.com/systemd/systemd/blob/main/src/core/bpf-firewall.c#L796#L799) program is loaded by firewall and device isolation programs

In the absence of probe helpers an alternative would be loading the program and relying on error code (`-ENOTSUP`?). IMO probing is more convenient since it gives a clear signal an exempts users from low-level BPF specifics like instructions of a trivial program.

**Comment by anakryiko** [comment]
The main problem right now is that all those feature-probing and helper APIs are little-known and barely anyone remembers about them (and I'm not even sure what's the state of tests for them). It would be good if you could assess how good/bad it is and what's missing. And then we should make them a first-class citizens that will need to be kept up to date and properly maintained.

**Comment by bluca** [comment]
Please, don't break API. We have merged usage of libbpf in systemd (and other places) with the understanding that it was stable and production ready. We have usages in stable releases out there. Breaking APIs means those won't work anymore, and for new ones we'll have to use a maze of ifdef'fery which ultimately reflects badly on the library itself. Nobody likes to use libraries that break compatibility :-)

It's understandable wanting to cleanup your implementation and so on - but could you please consider doing so while maintaining an internal shim that transparently translates old -> new without ABI breakages?

**Comment by anakryiko** [comment]
All this is in the context of a major version bump, at which point we are allowed to break ABI. If some users absolutely cannot adapt/migrate their code for some reason, they always will have an option to stick to 0.x version, right?

This is not the place to start the discussion again, but it is one of the reasons we keep recommending static linking against libbpf, so that you don't have to maintain unnecessary maze of ifdef'ery.

But which specific API breakage are you worried about?

**Comment by bluca** [comment]
I know that semantic versioning schemes theoretically allow for API breakage - it doesn't mean it has to happen though :-) Good libraries, stable and production ready, do not break API, ever. Things can change and be refactored, but with backward compat shims provided. I mean you are a kernel developer right? Just because the kernel version changes from 4 to 5 it doesn't mean you can break syscalls, no? There's no version semantic or technical limitation stopping that from happening, it's just a very good practice that was adopted - "we do not break userspace, ever". This is the same situation.

I mean as a maintainer of multiple libraries I can tell you with absolute certainty: no matter what version format you opt for, users are going to be extremely annoyed about API breaks. And I mean _extremely_. Been there, done that!

Quite honestly if I knew this could happen, I would have changed opinion from enthusiastically supporting and approving of merging usage of this into projects I maintain like systemd and others, to hard NACKs.

So what I am asking is to please reconsider the approach. It's not about this specific function or that, it's about the contract and the approach to maintenance. Unless when you suggest to stick to 0.x you mean that you are going to maintain a 0.x branch with security and bug fixes for the foreseeable future? That would be less bad, although still far from ideal.
