### ISSUE TITLE
Expose BPF_PROG_LOAD log_size and log_level?

### ISSUE THREAD

**Issue by rjmccabe3701** [libbpf/libbpf#37]
I'm not seeing an a mechanism by which to set the BPF_PROG_LOAD log_level and log_size.

So I modified the source a bit to set the ``log_level = 1``:

```patch
diff --git a/src/bpf.c b/src/bpf.c
index c70333f..dfd9cbc 100644
--- a/src/bpf.c
+++ b/src/bpf.c
@@ -238,6 +238,8 @@ int bpf_load_program_xattr(const struct bpf_load_program_attr *load_attr,
        attr.insns = ptr_to_u64(load_attr->insns);
        attr.license = ptr_to_u64(load_attr->license);

+
+       log_level = 1;
        attr.log_level = log_level;
        if (log_level) {
                attr.log_buf = ptr_to_u64(log_buf);
```

This change seems to expose an off-by-one error for ``BPF_LOG_BUF_SIZE`` 

For example, I am unable to load this trivial eBPF socket filter code:

```c
#include <linux/bpf.h>
#include "bpf_helpers.h"
SEC("dummy_socket_filter")
int socket_filter(struct __sk_buff *skb)
{
   return 0;
}
char _license[] SEC("license") = "GPL";

```

via this application:

```c
#include <bpf/libbpf.h>
#include <bpf/bpf.h>
#include <stdio.h>

int main(void)
{
   void* obj;
   struct bpf_object_open_attr open_attr;
   struct bpf_program* prog;

   open_attr.prog_type = BPF_PROG_TYPE_SOCKET_FILTER;
   open_attr.file = "dummy.o";

   obj = bpf_object__open_xattr(&open_attr);
   prog = bpf_object__find_program_by_title(obj, "dummy_socket_filter");

   bpf_program__set_type(prog, BPF_PROG_TYPE_SOCKET_FILTER);
   printf("load to kernel = %d\n", bpf_program__load(prog, "GPL", 0));
   return 0;
}
```

I get:

```
libbpf: load bpf program failed: Invalid argument
libbpf: failed to load program 'dummy_socket_filter'
load to kernel = -4009
```

It looks like this is due to a log buffer size [check](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/kernel/bpf/verifier.c?h=v4.19#n5935) in the kernel.  If I reduce the ``BPF_LOG_BUF_SIZE``, things work as expected 

```patch
diff --git a/src/bpf.h b/src/bpf.h
index bc30783..697f86a 100644
--- a/src/bpf.h
+++ b/src/bpf.h
@@ -92,7 +92,7 @@ struct bpf_load_program_attr {
 #define MAPS_RELAX_COMPAT      0x01

 /* Recommend log buffer size */
-#define BPF_LOG_BUF_SIZE (16 * 1024 * 1024) /* verifier maximum in kernels <= 5.1 */
+#define BPF_LOG_BUF_SIZE ((16 * 1024 * 1024) -1 ) /* verifier maximum in kernels <= 5.1 */
 LIBBPF_API int
 bpf_load_program_xattr(const struct bpf_load_program_attr *load_attr,
                       char *log_buf, size_t log_buf_sz);
```

**Comment by rdna** [comment]
From the pastes you provided I'm not even sure how the program reached that point since:
1) This BPF program should not be compilable since you use `socket_filter` both as a section name and as a function name. You should get something like: `LLVM ERROR: 'socket_filter' label emitted multiple times to assembly file`. To fix it you can use e.g. `SEC("socket")` instead of `SEC("socket_filter")`.
2) Since your program doesn't have section `"dummy_socket_filter"` `bpf_object__find_program_by_title` has no chances to succeed, so `prog` should be `NULL` and since it's passed to `bpf_program__set_type` w/o checking for `NULL`, it should just crash the program trying to dereference that `NULL`. Please make sure you find same string as used in `SEC`, e.g. `bpf_object__find_program_by_title(obj, "socket")` for `SEC("socket")`.

With these two changes it works:
```
% ./dummy_prog
load to kernel = 0
```

I believe `BPF_LOG_BUF_SIZE` is red-herring, it should not be relevant here.

**Comment by rjmccabe3701** [comment]
Sorry there was a typo in my original post (it is now fixed).

The same issue remains with ```4.15.0-47-generic``

**Comment by rdna** [comment]
I see. Yeah, you're right, the buffer was increased both [in the kernel](https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git/commit/kernel/bpf/verifier.c?id=7a9f5c65abcc9644b11738ca0815510cb5510eaf) and in [libbpf](https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git/commit/tools/lib/bpf/bpf.h?id=da11b417583ece875f862d84578259a2ab27ad86).
Since you use kernel w/o that patch but libbpf with the patch that breaks.

Yeah, it looks like off by one error in `BPF_LOG_BUF_SIZE` size in libbpf. You patch looks good, could you submit it to netdev@ please?

Cc: @4ast

**Comment by rjmccabe3701** [comment]
I spent a few hours trying to push this patch

```patch
From 03070a9063999bd851337d3cf9173e0dba7fc2b9 Mon Sep 17 00:00:00 2001
From: "McCabe, Robert J" <Robert.McCabe@rockwellcollins.com>
Date: Fri, 19 Apr 2019 09:43:45 -0500
Subject: [PATCH bpf-next] libbpf: fix BPF_LOG_BUF_SIZE off-by-one error

The BPF_PROG_LOAD condition for kernel version <= 5.1 is

   log->len_total > UINT_MAX >> 8 /* (16 * 1024 * 1024) - 1 */

Signed-off-by: rjmccabe3701 <robert.mccabe@rockwellcollins.com>
---
 tools/lib/bpf/bpf.h | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/tools/lib/bpf/bpf.h b/tools/lib/bpf/bpf.h
index bc30783d1403..62d67caa7aea 100644
--- a/tools/lib/bpf/bpf.h
+++ b/tools/lib/bpf/bpf.h
@@ -92,7 +92,7 @@ struct bpf_load_program_attr {
 #define MAPS_RELAX_COMPAT      0x01

 /* Recommend log buffer size */
-#define BPF_LOG_BUF_SIZE (16 * 1024 * 1024) /* verifier maximum in kernels <= 5.1 */
+#define BPF_LOG_BUF_SIZE ((16 * 1024 * 1024) - 1) /* verifier maximum in kernels <= 5.1 */
 LIBBPF_API int
 bpf_load_program_xattr(const struct bpf_load_program_attr *load_attr,
                       char *log_buf, size_t log_buf_sz);
--
2.17.1
```
via `` git send-email --to netdev@vger.kernel.org --cc robertjmccabe@gmail.com outgoing/*``

and I never could get it to show up here:

https://patchwork.ozlabs.org/project/netdev/list/?series=&state=%2A&delegate=&submitter=&archive=both

Not sure what I'm doing wrong.  I setup an account there a year or so ago and was able to push a patch to iproute2 ...

**Comment by rdna** [comment]
What you're doing looks fine, the only warning related to e-mail I see on the patch from `scripts/checkpatch.pl` is this:
```
WARNING: Missing Signed-off-by: line by nominal patch author 'McCabe, Robert J <Robert.McCabe@rockwellcollins.com>'
```
, so it might be a good idea to make sure e-mail in `From:` matches exactly e-mail in `Signed-off-by:`, otherwise `git send-email` does this:
```
Cc: "McCabe, Robert J" <Robert.McCabe@rockwellcollins.com>,
        rjmccabe3701 <robert.mccabe@rockwellcollins.com>
```

Do you see any problems reported in mail logs on your server after calling `git send-email` ?

If you still experience problems sending the patch, I can send it on your behalf with your SoB. Let me know if you need help with this.

**Comment by rjmccabe3701** [comment]
Apparently there is a few hours of delay from the the time i did ``git send-email`` to the time it shows up.  I spammed the list with the same patch:
https://patchwork.ozlabs.org/patch/1088155/
Here is the (likely) final patch:
https://patchwork.ozlabs.org/patch/1088252/

Thanks for the help.

**Comment by rjmccabe3701** [comment]
To answer my original question about the library not exposing the log level ... i was wrong.  This is a host loading program that prints the BPF_PROG_LOAD status:

```c
#include <bpf/libbpf.h>
#include <bpf/bpf.h>
#include <stdio.h>
#include <string.h>

static int libbpf_debug_print(enum libbpf_print_level level,
      const char *format, va_list args)
{
   /*Uncomment to not print all debug spam*/
   #if 0
   if (level == LIBBPF_DEBUG)
      return 0;
   #endif
   return vfprintf(stderr, format, args);
}

int main(void)
{
   struct bpf_prog_load_attr attr;
   struct bpf_object *obj;
   int prog_fd;
   int err;

   memset(&attr, 0, sizeof(struct bpf_prog_load_attr));
   attr.file = "dummy.o";
   attr.prog_type = BPF_PROG_TYPE_SCHED_CLS;
   attr.log_level = 4;
   libbpf_set_print(libbpf_debug_print);
   err = bpf_prog_load_xattr(&attr, &obj, &prog_fd);

   printf("load to kernel = %d, fd = %d\n", err, prog_fd);
   return 0;
}



```
I discovered this by browsing the libbpf usage in the kernel.  For example:

https://git.kernel.org/pub/scm/linux/kernel/git/bpf/bpf-next.git/tree/tools/testing/selftests/bpf/prog_tests/bpf_verif_scale.c
