### ISSUE TITLE
Nonfunctional headers installed

### ISSUE THREAD

**Issue by jengelh** [libbpf/libbpf#436]
Trying to build dwarves-1.23/pahole-1.23 yields this compile error incuded by libbpf-0.6.1:

```
[   29s] /usr/include/bpf/btf.h: In function 'btf_is_mod':
[   29s] /usr/include/bpf/btf.h:463:24: error: 'BTF_KIND_TYPE_TAG' undeclared (first use in this function); did you mean 'BTF_KIND_DECL_TAG'?
[   29s]   463 |                kind == BTF_KIND_TYPE_TAG;
```

libbpf is distributing a `btf.h` that makes use of `BTF_KIND_TYPE_TAG`, but this identifier is never defined.
The headers in `/usr/include/linux` are the uapi headers from 5.16, they also do not provide a definition for BTF_KIND_TYPE_TAG.

**Comment by tohojo** [comment]
Ran into this as well; BTF_KIND_TYPE_TAG isn't in the kernel headers until 5.17, but the commit referencing it is in libbpf 0.6.0...

**Comment by anakryiko** [comment]
Is it an option to use UAPI headers that libbpf itself is using? https://github.com/libbpf/libbpf/blob/master/include/uapi/linux/btf.h

For pahole specifically, though, we should probably make sure that it is using latest UAPI that are in libbpf repo.

**Comment by tohojo** [comment]
Not really, I think? When libbpf is packaged by distros, the libbpf package will include bpf/btf.h from libbpf but linux/btf.h will be whatever kernel headers the distro is shipping. You could add a hard dependency on a particular kernel header version for libbpf, but in this instance that doesn't help either because there is not a released kernel version with the define in to depend on.

So I think the correct fix is for the libbpf header to remove the dependency on the kernel header version altogether; so either by redefining the constants, or by making the kind check functions non-inline (so they can be hidden inside the compiled code).

**Comment by anakryiko** [comment]
That's what I suspected. Well, luckily it's mostly BTF constants that have this problem, I think we can #define them and they will co-exist with UAPI enum definitions as well. I'm not going to get to sending this patch in next few days, so if it's blocking please submit a patch, thanks!

**Comment by jengelh** [comment]
dwarves uses NR_BTF_KINDS, which has not gotten the same treatment as BTF_KIND_TYPE_TAG. (So, I'm still getting compile errors.)
```
11:35 a4:../dwarves/pahole $ grep -r NR_BTF_K /usr/include/linux/
/usr/include/linux/btf.h:       NR_BTF_KINDS,
/usr/include/linux/btf.h:       BTF_KIND_MAX            = NR_BTF_KINDS - 1,
11:35 a4:../dwarves/pahole $ grep -r BTF_KIND_MAX /usr/include/bpf/
```
(libbpf 0.7.0)

**Comment by anakryiko** [comment]
@jengelh, pahole should be modified to use latest Linux UAPI headers distributed with libbpf itself.
