### ISSUE TITLE
Invalid Read leads to Segmentation fault

### ISSUE THREAD

**Issue by rish9101** [libbpf/libbpf#700]
I found a bug at line 3600 of [libbpf.c](https://github.com/libbpf/libbpf/blob/ec6f716eda43fd0f4b865ddcebe0ce8cb56bf445/src/libbpf.c#L3600). This is caused due to one of the arguments to `strcmp` being a NULL Pointer.
The bug is triggered by fuzzing using the harness [bpf-object-fuzzer.c](https://github.com/libbpf/libbpf/blob/master/fuzz/bpf-object-fuzzer.c) provided in fuzz folder.

The stack trace of the execution is
```
#0  __strcmp_avx2 () at ../sysdeps/x86_64/multiarch/strcmp-avx2.S:101
#1  0x0000000000405ec7 in find_extern_btf_id (btf=0x44c1c0, ext_name=0x44aa94 "my_pid") at libbpf.c:3600
#2  bpf_object__collect_externs (obj=<optimized out>) at libbpf.c:3808
#3  bpf_object_open (path=<optimized out>, path@entry=0x0, obj_buf=<optimized out>, obj_buf_sz=<optimized out>, opts=<optimized out>) at libbpf.c:7376
#4  0x0000000000409bdb in bpf_object__open_mem (obj_buf=0x44aa94, obj_buf_sz=0x0, opts=0x0) at libbpf.c:7415
```
The crashing input has been attached below.

The bug has been tested on Ubuntu 20.04, libbpf built with clang-11. 

[null_ptr_strcmp.zip](https://github.com/libbpf/libbpf/files/11853030/null_ptr_strcmp.zip)

**Comment by anakryiko** [comment]
this should be addressed automatically once we implement https://github.com/libbpf/libbpf/issues/617

**Comment by rish9101** [comment]
I've also opened two other bug issues (#702 and #703). Will those be addressed by #617 too?

**Comment by anakryiko** [comment]
#703 would be addressed. #702 looks different and looking at the code it's not immediately clear what's going on, because we do have a check that rel is not NULL. Please feel free to investigate and suggest a fix (please send it to bpf@vger.kernel.org, BPF mailing list)

**Comment by evverx** [comment]
I've just received a gazillion notifications from OSS-Fuzz :-) and noticed this issue.

It was fixed. https://github.com/libbpf/libbpf/issues/703 was fixed too.

> The bug is triggered by fuzzing using the harness [bpf-object-fuzzer.c](https://github.com/libbpf/libbpf/blob/master/fuzz/bpf-object-fuzzer.c) provided in fuzz folder

@rish9101 this fuzz target is run on OSS-Fuzz continuously so all the bugs it can possibly trigger have already been reported one way or another. https://bugs.chromium.org/p/oss-fuzz/issues/list?q=label%3AProj-libbpf&can=1 is supposed to show all the bugs but due to the way OSS-Fuzz groups bug reports some bugs aren't there. (They are at https://oss-fuzz.com/testcases?project=libbpf). Anyway what I'm trying to say is that OSS-Fuzz founds issues, reports them and then verifies fixes automatically so it isn't necessary to report them manually.
